### ISSUE TITLE
value of parameters.insideTemperature

### ISSUE THREAD

**Issue by VesaliaBricks** [bisand/node-red-contrib-panasonic-comfort-cloud#18]
I understand the device node returns capabilities and settings of a single device.
The parameters field shows the current values of my AC.

However, the field parameters.insideTemperature shows a value of 126, which doesn't make sense as neither °C nor °F.
As I assume my AC has a thermometer for the inside temp (parameters.OUTTemperature looks plausible) for reaching its
target, I was wondering if there is a known conversion for it.

Other than that, I'm very happy with your package, thank you!
Sebastian

**Comment by bisand** [comment]
I have done some testing on my part and I can see correct values without any conversion. Not sure what the value you are receiving represents. Could it be a faulty sensor? Have you checked the values in the Panasonic app?
Here is a screenshot from the parameter values on my pump:
![image](https://github.com/bisand/node-red-contrib-panasonic-comfort-cloud/assets/376963/7532b28f-57ce-4fbc-bed1-5b2820ad7b90)

**Comment by VesaliaBricks** [comment]
Thank you for your response and for the latest migration!

Apparently, my older ACs do not provide their measured insideTemps and instead report 126. I have found this a few times in my searches. My newer AC reports correctly. In the App, the older ACs have a greyed out display for insideTemp without a value.

I guess I just couldn't imagine an AC not reporting their insideTemps. I mean, they must have it as they attempt to reach and maintain their target temp....

Have a nice weekend!
