### ISSUE TITLE
Bad request error

### ISSUE THREAD

**Issue by Sharppis1** [bisand/node-red-contrib-panasonic-comfort-cloud#19]
API response: {"code":"4000"，"message":"Missing required header parameter or bad request for header"}
Nothing has changed in node-red flow configs. In other panasonic cc related repo someone wrote that panasonic made some changes into API but also they made rollback. Not sure if so, but apparently rollback wasn't success...

**Comment by bisand** [comment]
I see that Panasonic has upgraded the app. Have you tried to restart NodeRed? I will try to improve the logic that handles the versioning, but in the meantime a NodeRed restart might help.

**Comment by hannuterasloihde** [comment]
I'm facing the same issue.  Also tested that the node implementation https://github.com/marc2016/panasonic-comfort-cloud-client has a working version, had to switch to that library temporarily to regain control of my heat pumps.

**Comment by bisand** [comment]
New version that addresses this issue is deployed. You might have to create a new credential in order to make it work.

**Comment by bisand** [comment]
Thanks to @mc02 for fixing this issue.

**Comment by xgcssch** [comment]
I had the same issue.
Updated to 1.5.0

But now i get:
`{"code":"4100","message":"Token expires","httpCode":401,"statusCode":401,"statusMessage":"Unauthorized"}`

I added a new credential, changed the password, but nothing helped.

Access via app is still possible.

Best regards
Sönke

**Comment by bisand** [comment]
I can't reproduce what you are experiencing. Have you tried to remove the config node and replace it with a new containing the correct credentials?

**Comment by xgcssch** [comment]
Recreating the config node did the job!
Thanks for the hint!
Sönke
