### ISSUE TITLE
Token expired, not updating

### ISSUE THREAD

**Issue by mongojarle** [bisand/node-red-contrib-panasonic-comfort-cloud#21]
Hi. The token has expired, and are not updated either.
I have updated the node to latest version, restarted NodeRed. I have also deleted the comfort cloud config and entered it again.

![image](https://github.com/bisand/node-red-contrib-panasonic-comfort-cloud/assets/41956509/eb927de1-0fc4-4165-bf2b-9d16d8642b8f)

**Comment by bisand** [comment]
New version that addresses this issue is deployed. You might have to create a new credential in order to make it work.

**Comment by mongojarle** [comment]
Thanks, works perfectly!
