### ISSUE TITLE
Device and Groups nodes returning a different set of parameters

### ISSUE THREAD

**Issue by hapination** [bisand/node-red-contrib-panasonic-comfort-cloud#24]
If I fetch the device parameters with the groups node I only get a subset of the parameters:
{"operate":1,"operationMode":3,"temperatureSet":8,"fanSpeed":5,"fanAutoMode":0,"airSwingLR":2,"airSwingUD":2,"ecoFunctionData":0,"ecoMode":0,"ecoNavi":0,"nanoe":0,"iAuto":0,"airDirection":1,"lastSettingMode":0}

When fetching the parameters with the device node for the same unit I get:
{"ecoFunctionData":0,"insideCleaning":0,"fireplace":0,"lastSettingMode":0,"operate":1,"operationMode":3,"temperatureSet":8,"fanSpeed":5,"fanAutoMode":0,"airSwingLR":2,"airSwingUD":2,"ecoMode":0,"ecoNavi":0,"nanoe":0,"iAuto":0,"airDirection":1,"insideTemperature":17,"outTemperature":8,"airQuality":0}

Could this be changed so that the same set parameters are returned regardless of which node is used to fetch the data. Mainly I'm interested in the inside/outside temperatures

**Comment by bisand** [comment]
This is what the Panasonic API returns. Any changes to this will require two calls to the API. I do not want to implement unnecessary API calls to the API because of the call rate limitation of the API. 
Sorry for the inconvenience.
