### ISSUE TITLE
NodeRed crash during ComfortCloud login() 

### ISSUE THREAD

**Issue by xgcssch** [bisand/node-red-contrib-panasonic-comfort-cloud#31]
Version 2.0.0

Hello!

Starting today NodeRed crashes in the extension.
It seems that Panasonic has changed something in the login process and the function `login()` of the `panasonic-comfort-cloud-client` library now throws an exception.
As the exception is not handled my NodeRed instance crashes.

```
2024/11/05 12:16:44,stdout,    at ComfortCloudDevice._inputCallback (/data/node_modules/node-red-contrib-panasonic-comfort-cloud/src/comfort-cloud-device.js:20:13)
2024/11/05 12:16:44,stdout,    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024/11/05 12:16:44,stdout,    at ComfortCloudClient.login (/data/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:66:18)
2024/11/05 12:16:44,stdout,    at ComfortCloudClient.handleError (/data/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:147:31)
```
There seems to be a matching issue opened at `panasonic-comfort-cloud-client`:  marc2016/panasonic-comfort-cloud-client#16

Best regards
Sönke

**Comment by xgcssch** [comment]
Hello @bisand!
Have you seen https://github.com/marc2016/panasonic-comfort-cloud-client/issues/16#issuecomment-2465621806?

**Comment by bisand** [comment]
I have just published a new version. Please give it a try and report back :)

**Comment by karivainio** [comment]
Earlier I got error 401, after upgrading to 2.0.3 I'm getting 429

10 Nov 14:16:44 - [red] Uncaught Exception:
10 Nov 14:16:44 - [error] ServiceError: Request failed with status code 429
undefined
    at ComfortCloudClient.handleError (/home/karivainio/.node-red/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:149:31)
    at ComfortCloudClient.login (/home/karivainio/.node-red/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:68:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ComfortCloudDevice._inputCallback (/home/karivainio/.node-red/node_modules/node-red-contrib-panasonic-comfort-cloud/src/comfort-cloud-device.js:20:13)

Node-RED v3.1.5
Node.js v18.20.4
Linux 6.1.21.-v7+ arm LE   running on RPI

Nothing to update on rasbian.
Should I upgrade something?

**Comment by karivainio** [comment]
> Earlier I got error 401, after upgrading to 2.0.3 I'm getting 429
> 
> 10 Nov 14:16:44 - [red] Uncaught Exception: 10 Nov 14:16:44 - [error] ServiceError: Request failed with status code 429 undefined at ComfortCloudClient.handleError (/home/karivainio/.node-red/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:149:31) at ComfortCloudClient.login (/home/karivainio/.node-red/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:68:18) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async ComfortCloudDevice._inputCallback (/home/karivainio/.node-red/node_modules/node-red-contrib-panasonic-comfort-cloud/src/comfort-cloud-device.js:20:13)
> 
> Node-RED v3.1.5 Node.js v18.20.4 Linux 6.1.21.-v7+ arm LE running on RPI
> 
> Nothing to update on rasbian. Should I upgrade something?

Got mail from Panasonic, that they block my account due consecutive login events! This is interesting as my node-red flow is currently triggering  comfort-cloud access only manually .  So seems that login is not correct.

**Comment by karivainio** [comment]
> > Earlier I got error 401, after upgrading to 2.0.3 I'm getting 429
> > 10 Nov 14:16:44 - [red] Uncaught Exception: 10 Nov 14:16:44 - [error] ServiceError: Request failed with status code 429 undefined at ComfortCloudClient.handleError (/home/karivainio/.node-red/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:149:31) at ComfortCloudClient.login (/home/karivainio/.node-red/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:68:18) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async ComfortCloudDevice._inputCallback (/home/karivainio/.node-red/node_modules/node-red-contrib-panasonic-comfort-cloud/src/comfort-cloud-device.js:20:13)
> > Node-RED v3.1.5 Node.js v18.20.4 Linux 6.1.21.-v7+ arm LE running on RPI
> > Nothing to update on rasbian. Should I upgrade something?
> 
> Got mail from Panasonic, that they block my account due consecutive login events! This is interesting as my node-red flow is currently triggering comfort-cloud access only manually . So seems that login is not correct.

Comfort-cloud password reset, and now access is working

**Comment by karivainio** [comment]
Thank you very much!

**Comment by xgcssch** [comment]
Hi André!

Updated to the new version and: works!
BTW: without password reset.

Thanks much!

Best regards
Sönke
