### ISSUE TITLE
403 error 

### ISSUE THREAD

**Issue by littlecake** [bisand/node-red-contrib-panasonic-comfort-cloud#9]
from today the app was broken, i log i found 
- TypeError: Cannot create property 'httpCode' on string '<html>^M
Jul 13 21:47:24 homematic daemon.err node-red: <head><title>403 Forbidden</title></head>^M
Jul 13 21:47:24 homematic daemon.err node-red: <body>^M
Jul 13 21:47:24 homematic daemon.err node-red: <center><h1>403 Forbidden</h1></center>^M
Jul 13 21:47:24 homematic daemon.err node-red: </body>^M
Jul 13 21:47:24 homematic daemon.err node-red: </html>^M

the problem "solved" by rewrite the /node_modules/panasonic-comfort-cloud-api/dist/ComfortCloud.js X-APP-VERSION to 1.50.0
i foud such information here:
https://github.com/lostfields/python-panasonic-comfort-cloud/pull/63/files

**Comment by smadds** [comment]
Wow - thank you so much, @littlecake . Our system also bombed today and that fix has got it working again... for now!

**Comment by littlecake** [comment]
Sorry, the problem apears again in next few hours, it needs to be solved other way

**Comment by shayneob** [comment]
I'm getting the same issue and it is crashing nodered completely.

**Comment by bisand** [comment]
A new updated version is published (1.3.0). This update includes improved error handling and automatic resolving of X-APP-VERSION. Thanks to @yodosan for PR and pointing me in the right direction.
Please update your installations and report back on the results.
Thanks!

**Comment by shayneob** [comment]
Install and the fix has everything back up and running, thanks heaps!
